language: ruby
rvm:
  - 1.9.3
  - 2.0.0
script: "rake spec"
env:
  - PUPPET_VERSION=3.1.0 FACTER_VERSION=1.7.6
  - PUPPET_VERSION=3.4.0 FACTER_VERSION=2.0.2
  - PUPPET_VERSION=3.6.0 FACTER_VERSION=2.1.0
  - PUPPET_VERSION=3.6.0 FACTER_VERSION=2.1.0 STRICT_VARIABLES=yes

gemfile: Gemfile
